### PR TITLE
Added support for RegularExpression, MaxLength, MinLength and FileExtensions attributes

### PR DESCRIPTION
**Pull request by Zhaph**
I noticed that the RegularExpression and FileExtension attributes aren't rendered correctly to support the out-of-the box validation methods in jV's additional-methods.js so I've added support for those.

I've also updated the Length support to also handle MinLength and MaxLength now that MVC 5.2.3 supports those attributes as well.

Tests and Demo's have also been updated (demo site in a separate commit).

Also noticed that the EqualTo test case was failing as you were no longer checking the custom error message.

I only updated the Demo & Test projects to MVC 5.2.3 as the core project didn't really need the additional dependency.

### CODE REVIEW

**Comment by johnnyreilly** [comment]
Cool - I'll try and take a look next week when I'm back near a computer. Ping me if I forget!

**Comment by johnnyreilly** [comment]
This is a really high quality pull request @Zhaph - thanks so much!  Merged with pleasure.

**Comment by johnnyreilly** [comment]
I've fixed up a couple of typos in the text, published to NuGet and given you a credit in the [change log](https://github.com/johnnyreilly/jQuery.Validation.Unobtrusive.Native#120--2015-06-08) and the [docs](http://johnnyreilly.github.io/jQuery.Validation.Unobtrusive.Native/Home/Download.html).

Thanks again for the pull request Ben.  It seems like we work pretty near to each other - I'm based in St James's and it sounds like you're pretty close by?

**Comment by Zhaph** [comment]
No worries - and well spotted on my copy/pasted typos :S Glad to help, and thanks for all the work you'd put into this to start with.

Based over in Shoreditch at the moment, so fairly close as these things go.

**Pull request merged**
